---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:13.1.2
  amd64: ghcr.io/hassio-addons/base/amd64:13.1.2
  armhf: ghcr.io/hassio-addons/base/armhf:13.1.2
  armv7: ghcr.io/hassio-addons/base/armv7:13.1.2
codenotary:
  signer: lmagyar1973@gmail.com
  base_image: codenotary@frenck.dev
