name: 'Test'

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7"]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Test build
      uses: home-assistant/builder@2022.07.0
      with:
        args: |
          --test \
          --no-latest \
          --${{ matrix.arch }} \
          --target portainer
      env:
        CAS_API_KEY: ${{ secrets.CAS_TOKEN }}
